from src.sql.operations import DatabaseOpp
from src.sql.models import Invoice

# Populate invoices table to ease the use of application
GOT_characters = [
    "Eddard Stark",
    "Catelyn Stark",
    "Robb Stark",
    "Sansa Stark",
    "Arya Stark",
    "Bran Stark",
    "Rickon Stark",
    "Jon Snow",
    "Daenerys Targaryen",
    "Viserys Targaryen",
    "Rhaegar Targaryen",
    "Aemon Targaryen",
    "Robert Baratheon",
    "Cersei Lannister",
    "Jaime Lannister",
    "Tyrion Lannister",
    "Tywin Lannister",
    "Joffrey Baratheon",
    "Tommen Baratheon",
    "Myrcella Baratheon",
    "Stannis Baratheon",
    "Renly Baratheon",
    "Selyse Baratheon",
    "Shiren Baratheon",
    "Margaery Tyrell",
    "Loras Tyrell",
    "Mace Tyrell",
    "Olenna Tyrell",
    "Petyr Baelish",
    "Varys",
    "Littlefinger",
    "Theon Greyjoy",
    "Yara Greyjoy",
    "Balon Greyjoy",
    "Euron Greyjoy",
    "Aeron Greyjoy",
    "Asha Greyjoy",
    "Sandor Clegane",
    "Gregor Clegane",
    "Beric Dondarrion",
    "Thoros of Myr",
    "Brienne of Tarth",
    "Podrick Payne",
    "Davos Seaworth",
    "Jorah Mormont",
    "Jeor Mormont",
    "Samwell Tarly",
    "Randyll Tarly",
    "Melisandre",
    "Stannis Baratheon",
    "Selyse Baratheon",
    "Shiren Baratheon",
    "Ramsay Bolton",
    "Roose Bolton",
    "Walder Frey",
    "The Night King",
    "Bran the Broken",
    "Hodor",
    "Meera Reed",
    "Jojen Reed",
    "Howland Reed",
    "Missandei",
    "Grey Worm",
    "Daario Naharis",
    "Hiizdahr zo Loraq",
    "Tormund Giantsbane",
    "Ygritte",
    "Lyanna Mormont",
    "Jeyne Westerling",
    "Talisa Maegyr",
    "Khal Drogo",
    "Viserys Targaryen",
    "Hot Pie",
    "Pycelle",
    "Qyburn",
    "Marillion",
    "Ros",
    "Osha",
    "Talysa Maegyr",
    "Jaqen H'ghar",
    "Rorge",
    "Biter",
    "The Waif",
    "The Faceless Man",
    "The Three-Eyed Raven",
    "The Old Nan",
    "Septa Mordane",
    "Septa Unella",
    "Maester Aemon",
    "Maester Luwin",
    "Margaery Tyrell",
    "Osha",
    "Lollys Stokeworth",
    "Alys Karstark",
    "Robett Glover",
    "Wyman Manderly",
    "Harald Karstark",
    "Theon Greyjoy",
    "Donnel Waynwood",
    "Bellamy",
    "Craster",
    "Ygritte",
    "Grenn",
    "Pyp",
    "Rast",
    "Dolorous Edd Tollett",
    "Luke Skywalker"
]

# Create random amount values to avoid duplicated transfers after the notice of credit
for character in GOT_characters:
    amount = len(character) * 100255 * (GOT_characters.index(character) if GOT_characters.index(character) != 0 else 1)
    tax_id = "01234567890"
    DatabaseOpp.insert_row({"amount": amount,
                            "tax_id": tax_id,
                            "name": character,
                            "invoice_sent": False},
                           Invoice)
