name: create_invoices

on:
  schedule:
    - cron 0 */3 9 29 3 2024 #runs every 3 hours at a specific day (2024-03-29)

concurrency:
  group: invoices
  cancel-in-progress: false

jobs:
  create_invoices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python -m pip install -r ../requirements.txt
        working-directory: ./routines

      - name: create_invoices.py
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          TYPE_OF_ENVIRONMENT: ${{ secrets.TYPE_OF_ENVIRONMENT }}
          URL_DATABASE: ${{ secrets.URL_DATABASE }}
          PYTHONPATH: .
        run: |
          python routines/create_invoices.py
          echo "create_invoices.py finished running"