#name: event_non_delivered
#
#on:
#  schedule:
#    - cron 0 23 * * * #runs every day at 8 p.m UTC-3
#
#concurrency:
#  group: events
#  cancel-in-progress: false
#
#jobs:
#  get_events:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.10'
#
#      - name: Install Python dependencies
#        run: |
#          python3 -m pip install --upgrade pip
#          python -m pip install -r ../requirements.txt
#        working-directory: ./routines
#
#      - name: event_non_delivered.py
#        env:
#          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
#          PROJECT_ID: ${{ secrets.PROJECT_ID }}
#          TYPE_OF_ENVIRONMENT: ${{ secrets.TYPE_OF_ENVIRONMENT }}
#          URL_DATABASE: ${{ secrets.URL_DATABASE }}
#          PYTHONPATH: .
#        run: |
#          python routines/event_non_delivered.py
#          echo "event_non_delivered.py finished running"